"""create activity_logs table

Revision ID: 141b74ef816a
Revises: e57d1c38078c
Create Date: 2026-04-17 04:09:12.189618

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "141b74ef816a"
down_revision: str | Sequence[str] | None = "e57d1c38078c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_logs",
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column(
            "action",
            sa.Enum(
                "login",
                "logout",
                "register",
                "password_reset",
                "document_upload",
                "document_delete",
                "document_processed",
                "job_create",
                "job_update",
                "job_delete",
                "candidate_create",
                "candidate_match",
                "application_status_change",
                name="activity_action",
            ),
            nullable=False,
        ),
        sa.Column("resource_type", sa.String(length=50), nullable=True),
        sa.Column("resource_id", sa.String(length=255), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_activity_logs_action"), "activity_logs", ["action"], unique=False
    )
    op.create_index(
        op.f("ix_activity_logs_actor_id"), "activity_logs", ["actor_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_activity_logs_actor_id"), table_name="activity_logs")
    op.drop_index(op.f("ix_activity_logs_action"), table_name="activity_logs")
    op.drop_table("activity_logs")
    op.execute("DROP TYPE IF EXISTS activity_action")
